// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:b88d119e-45e4-4134-8858-58d6c67a1019",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_iZAShJXkR",
    "aws_user_pools_web_client_id": "64enhrbg66bn2kqkl6oe8ibq2o",
    "oauth": {},
    "aws_mobile_analytics_app_id": "13aa7f110eb344059b8dbdbf5d711178",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
